// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0LsBMvL91IpR_R5qs2qtlehlH-idB6A',
    appId: '1:710019077654:web:f0954e917cd0590071c737',
    messagingSenderId: '710019077654',
    projectId: 'almabroorhajj-fe83a',
    authDomain: 'almabroorhajj-fe83a.firebaseapp.com',
    storageBucket: 'almabroorhajj-fe83a.firebasestorage.app',
    measurementId: 'G-6ZBGRDZ4YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-HjVvDEQDPkctWLDF20RI03Nsgnc0j_4',
    appId: '1:710019077654:android:7fe90617fd26e50271c737',
    messagingSenderId: '710019077654',
    projectId: 'almabroorhajj-fe83a',
    storageBucket: 'almabroorhajj-fe83a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdy4mCtJ0wotw3-U2Xtu-J8y6H0PMgTQo',
    appId: '1:710019077654:ios:70830908f867682171c737',
    messagingSenderId: '710019077654',
    projectId: 'almabroorhajj-fe83a',
    storageBucket: 'almabroorhajj-fe83a.firebasestorage.app',
    iosBundleId: 'com.example.almabroorhajj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdy4mCtJ0wotw3-U2Xtu-J8y6H0PMgTQo',
    appId: '1:710019077654:ios:70830908f867682171c737',
    messagingSenderId: '710019077654',
    projectId: 'almabroorhajj-fe83a',
    storageBucket: 'almabroorhajj-fe83a.firebasestorage.app',
    iosBundleId: 'com.example.almabroorhajj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE0LsBMvL91IpR_R5qs2qtlehlH-idB6A',
    appId: '1:710019077654:web:a2802502453c827b71c737',
    messagingSenderId: '710019077654',
    projectId: 'almabroorhajj-fe83a',
    authDomain: 'almabroorhajj-fe83a.firebaseapp.com',
    storageBucket: 'almabroorhajj-fe83a.firebasestorage.app',
    measurementId: 'G-1VGP20XSZT',
  );
}
